on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 18 */1 * *"

name: rules
jobs:
  sync:
    runs-on: ubuntu-22.04
    env:
      TZ: Europe/Busingen
    steps:
      
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Update
        run: |
          python3 skills-updater.py

      - name: Commit Changes
        run: |
          git config --local user.name "github-action[bot]"
          git config --local user.email "${{ secrets.EMAIL }}"
          git add .
          git commit -am "update on $(date)"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}